### ISSUE TITLE
Epic: More vector backends

### ISSUE THREAD

**Issue by abigail-hampson** [wagtail/wagtail-vector-index#45]
There are a number of other vector backend services we could consider integrating with. This epic covers reviewing whether an integration is viable/requested and building them.
```[tasklist]
### Tasks
- [ ] https://github.com/wagtail/wagtail-vector-index/issues/12
- [ ] https://github.com/wagtail/wagtail-vector-index/issues/47
- [ ] https://github.com/wagtail/wagtail-vector-index/issues/46
```
